runtime: python311
entrypoint: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT

env_variables:
  GOOGLE_CLOUD_PROJECT: "your-project-id"
  GOOGLE_CLOUD_LOCATION: "us-central1"
  USE_FIRESTORE: "true"
  LOG_LEVEL: "INFO"
  DEBUG_MODE: "false"

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
